# Site
title:              Chad & Szuyin
bio:                'May 20, 2017 - Ames, IA'
description:        "Chad and Szuyin are getting married!"
locale:             en_US
url:                http://chadandszuyin.us
email:              chadrknight+wedding@gmail.com

copyright: 'Chad &amp; Szuyin - 2017'
credits: 'Based on Landing Page, a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
# Jekyll
permalink:          /:title/
markdown:           kramdown

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, assets]
